# Site Specific Configuration
name: SelfCare Blog
description: A personal blog about self-care and wellness
url: https://yjhur.github.io
baseurl: /selfcare
author: 미듐레어
timezone: Asia/Seoul
timezone_short: KST

# Keywords
keywords: ['셀프케어', '웰니스', '정신건강', '자기계발', '라이프스타일', '마음챙김', '개인성장', '명상', '힐링']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Posts per page
  per_page: 5
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: ':에너지관리 카테고리의 포스트'
    permalink: 'selfcare/category/:energy'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

